export PATH="/workspaces/pixi_devcontainer/.pixi/envs/default/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export CONDA_PREFIX="/workspaces/pixi_devcontainer/.pixi/envs/default"
export PIXI_PROJECT_NAME="pixi_devcontainer"
export PIXI_PROJECT_MANIFEST="/workspaces/pixi_devcontainer/pyproject.toml"
export PIXI_PROJECT_VERSION="0.1.0"
export PIXI_PROJECT_ROOT="/workspaces/pixi_devcontainer"
export PIXI_EXE="/usr/local/bin/pixi"
export PIXI_IN_SHELL="1"
export CONDA_DEFAULT_ENV="pixi_devcontainer"
export PIXI_ENVIRONMENT_NAME="default"
export PIXI_ENVIRONMENT_PLATFORMS="linux-64"
export PIXI_PROMPT="(pixi_devcontainer) "

